name: flutter_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  dio: ^5.0.0
  get_storage: ^2.0.3
  google_fonts: ^4.0.3
  hexcolor: ^2.0.7
  http: ^0.13.5
  lottie: ^1.4.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

